nodeLinker: node-modules
enableGlobalCache: true

yarnPath: .yarn/releases/yarn-3.6.3.cjs

packageExtensions:
  "@vue/devtools-core@*":
    peerDependencies:
      vite: "*"
  "vite-plugin-vue-devtools@*":
    peerDependencies:
      vue: "*"
  "@vitest/eslint-plugin@*":
    peerDependencies:
      "@typescript-eslint/utils": "*" 