nodeLinker: node-modules
enableGlobalCache: false

packageExtensions:
  "@vue/devtools-core@*":
    peerDependencies:
      vite: "*"
  "vite-plugin-vue-devtools@*":
    peerDependencies:
      vue: "*"
  "@vitest/eslint-plugin@*":
    peerDependencies:
      "@typescript-eslint/utils": "*" 